name: Go
on: [push]
jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '^1.15.7'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Do checking
      run: make check-ci
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.36

